export const categoryItems = [
      {
        title: '喜剧',
        id: 101,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '爱情',
        id: 102,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '动作',
        id: 103,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '犯罪',
        id: 104,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '科幻',
        id: 105,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '奇幻',
        id: 106,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '冒险',
        id: 107,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '灾难',
        id: 108,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '惊悚',
        id: 109,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '剧情',
        id: 110,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '战争',
        id: 111,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '歌舞',
        id: 112,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '经典',
        id: 113,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '悬疑',
        id: 114,
        routerLink: '/pages/list',
        channel: '1',
      },
      {
        title: '动画电影',
        id: 115,
        routerLink: '/pages/list',
        channel: '1',
      },

      {
        title: '国产剧',
        id: 201,
        routerLink: '/pages/list',
        channel: '2',
      },
      {
        title: '港台剧',
        id: 202,
        routerLink: '/pages/list',
        channel: '2',
      },
      {
        title: '日韩剧',
        id: 203,
        routerLink: '/pages/list',
        channel: '2',
      },
      {
        title: '欧美剧',
        id: 204,
        routerLink: '/pages/list',
        channel: '2',
      },
      {
        title: '新马泰',
        id: 205,
        routerLink: '/pages/list',
        channel: '2',
      },
      {
        title: '其他剧',
        id: 206,
        routerLink: '/pages/list',
        channel: '2',
      },
      {
        title: '访谈',
        id: 301,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: '选秀',
        id: 302,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: '搞笑',
        id: 303,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: 'MV',
        id: 304,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: '晚会',
        id: 305,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: '竞技',
        id: 306,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: '情感',
        id: 307,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: '演唱会',
        id: 308,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: '真人秀',
        id: 309,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: '脱口秀',
        id: 310,
        routerLink: '/pages/list',
        channel: '3',
      },
      {
        title: '热血',
        id: 401,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '格斗',
        id: 402,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '机战',
        id: 403,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '少女',
        id: 404,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '竞技',
        id: 405,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '科幻',
        id: 406,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '魔幻',
        id: 407,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '爆笑',
        id: 408,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '推理',
        id: 409,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '灵异',
        id: 410,
        routerLink: '/pages/list',
        channel: '4',
      },
      {
        title: '奥运',
        id: 501,
        routerLink: '/pages/list',
        channel: '5',
      },
      {
        title: '综合',
        id: 502,
        routerLink: '/pages/list',
        channel: '5',
      },
      {
        title: '篮球',
        id: 503,
        routerLink: '/pages/list',
        channel: '5',
      },
      {
        title: '足球',
        id: 504,
        routerLink: '/pages/list',
        channel: '5',
      },
      {
        title: '文化',
        id: 505,
        routerLink: '/pages/list',
        channel: '5',
      },
      {
        title: '探索',
        id: 506,
        routerLink: '/pages/list',
        channel: '5',
      },
      {
        title: '军事',
        id: 507,
        routerLink: '/pages/list',
        channel: '5',
      },
      {
        title: '解密',
        id: 508,
        routerLink: '/pages/list',
        channel: '5',
      },
      {
        title: '科技',
        id: 509,
        routerLink: '/pages/list',
        channel: '5',
      },
      {
        title: '历史',
        id: 601,
        routerLink: '/pages/list',
        channel: '6',
      },
      {
        title: '人物',
        id: 602,
        routerLink: '/pages/list',
        channel: '6',
      },
      {
        title: '自然',
        id: 603,
        routerLink: '/pages/list',
        channel: '6',
      },
      {
        title: '动态',
        id: 701,
        routerLink: '/pages/list',
        channel: '7',
      },
      {
        title: '生活',
        id: 702,
        routerLink: '/pages/list',
        channel: '7',
      },
      {
        title: '华人风采',
        id: 703,
        routerLink: '/pages/list',
        channel: '7',
      },
      {
        title: '比赛',
        id: 704,
        routerLink: '/pages/list',
        channel: '7',
      },
      {
        title: '演出',
        id: 705,
        routerLink: '/pages/list',
        channel: '7',
      },
      {
        title: '网游/单机',
        id: 801,
        routerLink: '/pages/list',
        channel: '8',
      },
      {
        title: '炉石传说',
        id: 802,
        routerLink: '/pages/list',
        channel: '8',
      },
      {
        title: '游戏预告',
        id: 803,
        routerLink: '/pages/list',
        channel: '8',
      },
      {
        title: 'China Joy',
        id: 804,
        routerLink: '/pages/list',
        channel: '8',
      },
      {
        title: '英雄联盟',
        id: 805,
        routerLink: '/pages/list',
        channel: '8',
      },
      {
        title: 'DOTA2',
        id: 806,
        routerLink: '/pages/list',
        channel: '8',
      }
];
